-- 코드를 입력하세요
-- SELECT
-- FROM USED_GOODS_BOARD A
-- JOIN USED_GOODS_FILE B
-- ON A.BOARD_ID = B.BOARD_ID

SELECT '/home/grep/src/' || BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT  "FILE_PATH"
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
    SELECT A.BOARD_ID
    FROM (
        SELECT *
        FROM USED_GOODS_BOARD
        ORDER BY VIEWS DESC
    ) A
    JOIN USED_GOODS_FILE B
    ON A.BOARD_ID = B.BOARD_ID
    WHERE ROWNUM = 1
)
ORDER BY FILE_ID DESC