-- 코드를 입력하세요
SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT A
JOIN APPOINTMENT B
ON A.PT_NO = B.PT_NO
JOIN DOCTOR C
ON C.DR_ID = B.MDDR_ID
WHERE B.APNT_CNCL_YN = 'N' AND TO_CHAR(B.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND C.MCDP_CD = 'CS'
ORDER BY B.APNT_YMD