-- 코드를 입력하세요
SELECT CAR_ID, 
    MAX(CASE 
        WHEN TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16' 
        AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16' THEN '대여중'
        ELSE '대여 가능'
    END) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC