SELECT EXTRACT(YEAR FROM B.SALES_DATE) YEAR, 
       EXTRACT(MONTH FROM B.SALES_DATE) MONTH, 
       A.GENDER, 
       COUNT(DISTINCT A.USER_ID) USERS
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM B.SALES_DATE), EXTRACT(MONTH FROM B.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, GENDER