-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
AND A.PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT B
    WHERE A.CATEGORY = B.CATEGORY
)
ORDER BY MAX_PRICE DESC