SELECT B.USER_ID, B.NICKNAME, CONCAT(CONCAT(CONCAT(CONCAT(CITY, ' '), STREET_ADDRESS1), ' '), STREET_ADDRESS2) "전체주소", CONCAT(CONCAT(CONCAT(CONCAT(SUBSTR(TLNO, 1, 3), '-'), SUBSTR(TLNO, 4, 4)), '-'), SUBSTR(TLNO, 8, 4)) "TLNO"
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.WRITER_ID IN (
    SELECT A.WRITER_ID
    FROM USED_GOODS_BOARD A
    JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
    GROUP BY A.WRITER_ID
    HAVING COUNT(*) >= 3
)
GROUP BY B.USER_ID, B.NICKNAME, "전체주소", "TLNO"
ORDER BY B.USER_ID DESC