-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, B.CITY || ' ' || B.STREET_ADDRESS1 || ' '|| B.STREET_ADDRESS2, SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) "전화번호"
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID, B.NICKNAME, B.CITY, B.STREET_ADDRESS1, B.STREET_ADDRESS2, TLNO
HAVING COUNT(*) >= 3
ORDER BY B.USER_ID DESC
-- SELECT *
-- FROM USED_GOODS_USER
-- WHERE NICKNAME = '찐찐'
-- 01053422914