SELECT FLAVOR
FROM (
    SELECT A.FLAVOR, A.TOTAL_ORDER + SUM(B.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF A
    JOIN JULY B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR, A.TOTAL_ORDER
    ORDER BY TOTAL DESC
)
WHERE ROWNUM <= 3